version: "2"
run:
  tests: false
linters:
  default: all
  disable:
    - depguard
    - mnd
  settings:
    lll:
      line-length: 140
    tagliatelle:
      case:
        rules:
          json: snake
          whatever: kebab
          xml: camel
          yaml: camel
        use-field-name: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - nilnil
        path: internal/kubernetes/k8s.go
      - linters:
          - ireturn
        path: internal/exporters/domain/metrics/metrics.go
      - linters:
          - gochecknoglobals
        path: internal/application/app.go
      - linters:
          - exhaustruct
          - forcetypeassert
          - gochecknoglobals
          - gosec
          - mnd
          - perfsprint
          - wrapcheck
        path-except: internal/appkit/unittests\.go
      - linters:
          - exhaustruct
          - forcetypeassert
          - gochecknoglobals
          - gosec
          - mnd
          - perfsprint
          - varnamelen
          - wrapcheck
        path-except: internal/appkit/e2etests\.go
    paths:
      - internal/sdk/unittests/fakekubelet/podresources.go
      - internal/sdk/unittests/k8sfixtures/fixture.go
      - internal/sdk/unittests/metricfixtures/fixture.go
      - internal/amd/cpustat.go
      - internal/amd/goamdsmi/file.go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - internal/sdk/unittests/fakekubelet/podresources.go
      - internal/sdk/unittests/k8sfixtures/fixture.go
      - internal/sdk/unittests/metricfixtures/fixture.go
      - internal/amd/cpustat.go
      - internal/amd/goamdsmi/file.go
      - third_party$
      - builtin$
      - examples$
